// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTU2Sq5N0BcSZ3pZI7uXTt0ZobsxhGZ7k',
    appId: '1:269993015075:web:863504ae1bda78c50dbe96',
    messagingSenderId: '269993015075',
    projectId: 'kigali-services-app',
    authDomain: 'kigali-services-app.firebaseapp.com',
    storageBucket: 'kigali-services-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2Ryi-ZmE8lcJBPJhEZ0AdNcLvmBDOPg',
    appId: '1:269993015075:ios:362a999d85a4f11f0dbe96',
    messagingSenderId: '269993015075',
    projectId: 'kigali-services-app',
    storageBucket: 'kigali-services-app.firebasestorage.app',
    iosBundleId: 'com.example.kigaliServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2Ryi-ZmE8lcJBPJhEZ0AdNcLvmBDOPg',
    appId: '1:269993015075:ios:362a999d85a4f11f0dbe96',
    messagingSenderId: '269993015075',
    projectId: 'kigali-services-app',
    storageBucket: 'kigali-services-app.firebasestorage.app',
    iosBundleId: 'com.example.kigaliServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTU2Sq5N0BcSZ3pZI7uXTt0ZobsxhGZ7k',
    appId: '1:269993015075:web:cd7f3dfb88a2f69f0dbe96',
    messagingSenderId: '269993015075',
    projectId: 'kigali-services-app',
    authDomain: 'kigali-services-app.firebaseapp.com',
    storageBucket: 'kigali-services-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2_A5GZH3ZaoBmCOpgG8PSO25VChdNFLM',
    appId: '1:269993015075:android:d8ca4bca124646c40dbe96',
    messagingSenderId: '269993015075',
    projectId: 'kigali-services-app',
    storageBucket: 'kigali-services-app.firebasestorage.app',
  );

}